In [19]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report

In [20]:
train_data = pd.read_csv("/kaggle/input/genre-classification-dataset-imdb/Genre Classification Dataset/train_data.txt",sep=':::',names=['Id', 'Title', 'Genre', 'Description'])
display(train_data.head())
print(train_data.shape)
train_data.isna().sum() 
train_data['Genre'].unique()

/tmp/ipykernel_33/3769998930.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  train_data = pd.read_csv("/kaggle/input/genre-classification-dataset-imdb/Genre Classification Dataset/train_data.txt",sep=':::',names=['Id', 'Title', 'Genre', 'Description'])

,Id,Title,Genre,Description
0,1,Oscar et la dame rose (2009),drama,Listening in to a conversation between his do...
1,2,Cupid (1997),thriller,A brother and sister with a past incestuous r...
2,3,"Young, Wild and Wonderful (1980)",adult,As the bus empties the students for their fie...
3,4,The Secret Sin (1915),drama,To help their unemployed father make ends mee...
4,5,The Unrecovered (2007),drama,The film's title refers not only to the un-re...

(54214, 4)

array([' drama ', ' thriller ', ' adult ', ' documentary ', ' comedy ',
       ' crime ', ' reality-tv ', ' horror ', ' sport ', ' animation ',
       ' action ', ' fantasy ', ' short ', ' sci-fi ', ' music ',
       ' adventure ', ' talk-show ', ' western ', ' family ', ' mystery ',
       ' history ', ' news ', ' biography ', ' romance ', ' game-show ',
       ' musical ', ' war '], dtype=object)

In [21]:
test_data = pd.read_csv("/kaggle/input/genre-classification-dataset-imdb/Genre Classification Dataset/test_data.txt",sep=':::',names=['Id', 'Title', 'Description'])
display(test_data.head())
print(test_data.shape)
test_data.isna().sum()

/tmp/ipykernel_33/3081141428.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  test_data = pd.read_csv("/kaggle/input/genre-classification-dataset-imdb/Genre Classification Dataset/test_data.txt",sep=':::',names=['Id', 'Title', 'Description'])

,Id,Title,Description
0,1,Edgar's Lunch (1998),"L.R. Brane loves his life - his car, his apar..."
1,2,La guerra de papá (1977),"Spain, March 1964: Quico is a very naughty ch..."
2,3,Off the Beaten Track (2010),One year in the life of Albin and his family ...
3,4,Meu Amigo Hindu (2015),"His father has died, he hasn't spoken with hi..."
4,5,Er nu zhai (1955),Before he was known internationally as a mart...

(54200, 3)

Id             0
Title          0
Description    0
dtype: int64

In [22]:
test_solution_data = pd.read_csv("/kaggle/input/genre-classification-dataset-imdb/Genre Classification Dataset/test_data_solution.txt",sep=':::',names=['Id', 'Title', 'Genre','Description'])
display(test_solution_data.head())
print(test_solution_data.shape)
test_solution_data.isna().sum()

/tmp/ipykernel_33/3089342271.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  test_solution_data = pd.read_csv("/kaggle/input/genre-classification-dataset-imdb/Genre Classification Dataset/test_data_solution.txt",sep=':::',names=['Id', 'Title', 'Genre','Description'])

,Id,Title,Genre,Description
0,1,Edgar's Lunch (1998),thriller,"L.R. Brane loves his life - his car, his apar..."
1,2,La guerra de papá (1977),comedy,"Spain, March 1964: Quico is a very naughty ch..."
2,3,Off the Beaten Track (2010),documentary,One year in the life of Albin and his family ...
3,4,Meu Amigo Hindu (2015),drama,"His father has died, he hasn't spoken with hi..."
4,5,Er nu zhai (1955),drama,Before he was known internationally as a mart...

(54200, 4)

Id             0
Title          0
Genre          0
Description    0
dtype: int64

In [23]:
class_distribution = train_data['Genre'].value_counts()
print(class_distribution)

Genre
drama           13613
documentary     13096
comedy           7447
short            5073
horror           2204
thriller         1591
action           1315
western          1032
reality-tv        884
family            784
adventure         775
music             731
romance           672
sci-fi            647
adult             590
crime             505
animation         498
sport             432
talk-show         391
fantasy           323
mystery           319
musical           277
biography         265
history           243
game-show         194
news              181
war               132
Name: count, dtype: int64

In [24]:
tfidf_vectorizer = TfidfVectorizer(max_features=5000)
X_train_tfidf = tfidf_vectorizer.fit_transform(train_data['Description'])
y_train = train_data['Genre']  

nb_classifier = MultinomialNB()
nb_classifier.fit(X_train_tfidf, y_train)
y_train_pred = nb_classifier.predict(X_train_tfidf)

print("Accuracy on training set:", accuracy_score(y_train, y_train_pred))
print("Classification Report on training set:\n", classification_report(y_train, y_train_pred))

Accuracy on training set: 0.5359132327443096

/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Classification Report on training set:
                precision    recall  f1-score   support

      action        0.70      0.09      0.16      1315
       adult        0.79      0.05      0.10       590
   adventure        0.76      0.05      0.10       775
   animation        0.00      0.00      0.00       498
   biography        0.00      0.00      0.00       265
      comedy        0.56      0.45      0.50      7447
       crime        0.00      0.00      0.00       505
 documentary        0.57      0.90      0.70     13096
       drama        0.47      0.84      0.60     13613
      family        1.00      0.00      0.01       784
     fantasy        0.00      0.00      0.00       323
   game-show        1.00      0.14      0.24       194
     history        0.00      0.00      0.00       243
      horror        0.78      0.36      0.50      2204
       music        0.90      0.16      0.27       731
     musical        0.00      0.00      0.00       277
     mystery        0.00      0.00      0.00       319
        news        0.00      0.00      0.00       181
  reality-tv        0.85      0.03      0.05       884
     romance        0.00      0.00      0.00       672
      sci-fi        0.85      0.04      0.09       647
       short        0.66      0.11      0.19      5073
       sport        0.80      0.11      0.19       432
   talk-show        1.00      0.01      0.02       391
    thriller        0.71      0.02      0.05      1591
         war        0.00      0.00      0.00       132
     western        0.97      0.59      0.73      1032

     accuracy                           0.54     54214
    macro avg       0.50      0.15      0.17     54214
 weighted avg       0.57      0.54      0.46     54214

/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [25]:
tfidf_vectorizer = TfidfVectorizer(max_features=5000)
X_test = tfidf_vectorizer.fit_transform(test_data['Description'])

In [26]:
 X_test_predictions = nb_classifier.predict(X_test)
test_data['Predicted_Genre'] = X_test_predictions
print(test_data)

          Id                             Title  \
0          1             Edgar's Lunch (1998)
1          2         La guerra de papá (1977)
2          3      Off the Beaten Track (2010)
3          4           Meu Amigo Hindu (2015)
4          5                Er nu zhai (1955)
...      ...                               ...
54195  54196   "Tales of Light & Dark" (2013)
54196  54197      Der letzte Mohikaner (1965)
54197  54198              Oliver Twink (2007)
54198  54199                Slipstream (1973)
54199  54200        Curitiba Zero Grau (2010)

                                             Description Predicted_Genre
0       L.R. Brane loves his life - his car, his apar...          drama
1       Spain, March 1964: Quico is a very naughty ch...          drama
2       One year in the life of Albin and his family ...    documentary
3       His father has died, he hasn't spoken with hi...    documentary
4       Before he was known internationally as a mart...    documentary
...                                                  ...             ...
54195   Covering multiple genres, Tales of Light & Da...          drama
54196   As Alice and Cora Munro attempt to find their...          drama
54197   A movie 169 years in the making. Oliver Twist...    documentary
54198   Popular, but mysterious rock D.J Mike Mallard...          drama
54199   Curitiba is a city in movement, with rhythms ...          short

[54200 rows x 4 columns]